spring:
  profiles:
    active: dev

logging:
  level:
    root: info
  file:
    name: log/blog.log

#MyBatis-Plus相关配置
#mybatis-plus:
#  configuration:
#    #配置日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl