spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhihu?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: maomao
  profiles:
    active: pro

logging:
  level:
    root: info
  file:
    name: log/blog.log

---
server:
  #端口号
  port: 8080
spring:
  profiles: pro
---